### ISSUE TITLE
项目clone下来，跑起来后点击切换主题的两个按钮，页面没反应

### ISSUE THREAD

**Issue by seed-fe** [yitimo/dynamic-antd-theme-sample#1]
您好，把您这个项目clone下来，npm start跑起来以后，点击页面里切换主题色的两个按钮，页面没反应，貌似生成的color.less文件是空的，请问是什么问题？

**Comment by yitimo** [comment]
> 您好，把您这个项目clone下来，npm start跑起来以后，点击页面里切换主题色的两个按钮，页面没反应，貌似生成的color.less文件是空的，请问是什么问题？

原工程和依赖都已经过于陈旧, 已修复更新到了master, 关注 ``antd-theme-webpack-plugin`` 配置.

**Comment by yitimo** [comment]
Close for it runs correctly now.

**Comment by yitimo** [comment]
Close for it runs correctly now.
